### ISSUE TITLE
Confusing date format

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#111]
The current date format mm/dd/yyyy is confusing to anyone who is not based in the US.  I recommend we switch to dd Month yyyy.  This would make 2/4/2018 4 February 2018, and ensure it is not mistaken for 2 April 2018.

**Comment by rstoneback** [comment]
Fair point, I support the change.

Only technical concern I have is windows compatibility. Some of the date printing codes have unexpected gotchas but I’m sure that can be sorted.
I mention it because I ran into that very issue on the date printing lines you’ve brought up.

On Nov 9, 2018, at 9:21 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


The current date format mm/dd/yyyy is confusing to anyone who is not based in the US. I recommend we switch to dd Month yyyy. This would make 2/4/2018 4 February 2018, and ensure it is not mistaken for 2 April 2018.

**Comment by aburrell** [comment]
That's an interesting feature that %x has.  However, I can see people second guessing the date format if they know it's written by Americans.  So I still think the unambiguous date format is preferable.

**Comment by rstoneback** [comment]
Your suggested format has been implemented in the files_upgrade branch. It looks good. Thanks.


On Dec 6, 2018, at 9:13 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


That's an interesting feature that %x has. However, I can see people second guessing the date format if they know it's written by Americans. So I still think the unambiguous date format is preferable.

**Comment by rstoneback** [comment]
Included in pull #128
