### ISSUE TITLE
f107 prelim file time range

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#161]
There is an issue with the prelim F10.7 files that I don't know how to solve.  The most recent prelim file is updated regularly until the quarter is over.  This means that the file name is the same, and the period of time the file is valid for is technically the same, but new data is entering remotely.  Because list_files doesn't look inside the file to get the last day, it can only know the range the local file is valid for.  How can I fix this, so that the file is downloaded again when I use update_files=True?

**Comment by rstoneback** [comment]
We may want to update the update_files keyword. It used to be update_file_list because all it does is refresh pysat's knowledge of the local files. Now that some services have expanded, update_files may not be the best. Well, it may never have been the best.

If you want to automatically keep f107 prelim updated, then you can include a call to inst.download_updated_files() in the instrument support init() call. This will always run unless you hide it under a keyword check. Since it is a small file that may not be a problem, though an error shouldn't stop the overall flow. Someone may choose to work in a park one day.

The update_files keyword is not currently attached to the instrument object. It is simply passed to the Files Class, which only uses it to invoke a self.reresh() call. It is lost to the ether.  

That should cover how things are. 

To do better we'll have to make some pysat changes.

**Comment by aburrell** [comment]
I found a different solution.  I updated the download routine to allow a file overwrite if the date range of the file extends past today.  If you don't call download, everything will be the same.  If you do, then your file will be updated.

**Comment by aburrell** [comment]
Solution waiting for Travis and review in #166

**Comment by rstoneback** [comment]
That’s good, especially since the solution I offered probably wouldn’t work in this case. Filenames are probably the same on server and locally, based on your description, so the newness probably wouldn’t be recognized.


On Feb 21, 2019, at 1:52 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


I found a different solution. I updated the download routine to allow a file overwrite if the date range of the file extends past today. If you don't call download, everything will be the same. If you do, then your file will be updated.

**Comment by aburrell** [comment]
Yeah, I was writing up a list_remote_files routine and thought "wait, what?".  But it got me on the right track.

**Comment by rstoneback** [comment]
Good to hear.

Cheers.


On Feb 22, 2019, at 7:20 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:

Yeah, I was writing up a list_remote_files routine and thought "wait, what?". But it got me on the right track.
