### ISSUE TITLE
Downloading Madrigal Data

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#172]
I keep running into this issue, where I can't download Madrigal data using pysat because it can't find globalDownload.py.  I have no idea why it can't find globalDownload.py, since it is installed and has worked on this computer before.  Any idea what could be going on?

**Comment by rstoneback** [comment]
Not offhand. Wish I had something better than a suggestion to reinstall MadrigalWeb or openMadrigal. I always forget which is the correct name.

GlobalDownload should be available from the standard terminal command line if it is installed.

On Feb 22, 2019, at 8:19 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


I keep running into this issue, where I can't download Madrigal data using pysat because it can't find globalDownload.py. I have no idea why it can't find globalDownload.py, since it is installed and has worked on this computer before. Any idea what could be going on?

**Comment by aburrell** [comment]
Uninstalled and reinstalled (both using pip and downloading the source code and installing).  No success.  Very sad.

**Comment by aburrell** [comment]
Ok.  Tears aside, I dug into my path and cleaned it up.  Remade symbolic links.  Fingers crossed.

**Comment by rstoneback** [comment]
Good luck!

On Feb 22, 2019, at 9:55 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok. Tears aside, I dug into my path and cleaned it up. Remade symbolic links. Fingers crossed.

**Comment by aburrell** [comment]
And it works.  For the future, if you have installed madrigalWeb and downloadGlobal.py isn't showing up, try checking:

- Your path for a bin directory where downloadGlobal lives (close to where the site-packages live, but not the same place)
- The alias or symbolic link for your default python command (since these need to match).

**Comment by rstoneback** [comment]
Awesome!

Thanks for recording the tips.

On Feb 22, 2019, at 9:57 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


And it works. For the future, if you have installed madrigalWeb and downloadGlobal.py isn't showing up, try checking:

  *   Your path for a bin directory where downloadGlobal lives (close to where the site-packages live, but not the same place)
  *   The alias or symbolic link for your default python command (since these need to match).
