### ISSUE TITLE
OMNI HRO not loading

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#19]
OMNI HRO data is not loading when "with" statement is present.

This has happened on both my Mac OSX Sierra machines.  The error I get is:

In [172]: omni.load(date=dtime)

AttributeError                            Traceback (most recent call last)
<ipython-input-172-bea02382d776> in <module>()
----> 1 omni.load(date=dtime)

/Users/ab763/Programs/Git/pysat/pysat/_instrument.py in load(self, yr, doy, date, fname, fid, verifyPad)
    742         # if self.pad is False, load single day
    743         else:
--> 744             self.data, meta = self._load_data(date=self.date, fid=self._fid)
    745             if not self.data.empty:
    746                 self.meta = meta

/Users/ab763/Programs/Git/pysat/pysat/_instrument.py in _load_data(self, date, fid)
    506             load_fname = [os.path.join(self.files.data_path, f) for f in fname]
    507             data, mdata = self._load_rtn(load_fname, tag=self.tag,
--> 508                                          sat_id=self.sat_id, **self.kwargs)
    509         else:
    510             data = DataFrame(None)

/Users/ab763/Programs/Git/pysat/pysat/instruments/omni_hro.py in load(fnames, tag, sat_id)
    120         fname = fnames[0][0:-11]
    121         date = pysat.datetime.strptime(fnames[0][-10:], '%Y-%m-%d')
--> 122         with pysatCDF.CDF(fname) as cdf:
    123             data, meta = cdf.to_pysat()
    124             # pick out data for date

AttributeError: __exit__

And this went away when I removed the "with" statement.

**Comment by rstoneback** [comment]
With is made for opening files... and the code passed testing on CI.  Maybe pysatCDF has an issue.....

On Mar 26, 2018, at 7:34 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


OMNI HRO data is not loading when "with" statement is present.

This has happened on both my Mac OSX Sierra machines. The error I get is:

In [172]: omni.load(date=dtime)

AttributeError Traceback (most recent call last)
in ()
----> 1 omni.load(date=dtime)

/Users/ab763/Programs/Git/pysat/pysat/_instrument.py in load(self, yr, doy, date, fname, fid, verifyPad)
742 # if self.pad is False, load single day
743 else:
--> 744 self.data, meta = self._load_data(date=self.date, fid=self._fid)
745 if not self.data.empty:
746 self.meta = meta

/Users/ab763/Programs/Git/pysat/pysat/_instrument.py in _load_data(self, date, fid)
506 load_fname = [os.path.join(self.files.data_path, f) for f in fname]
507 data, mdata = self._load_rtn(load_fname, tag=self.tag,
--> 508 sat_id=self.sat_id, **self.kwargs)
509 else:
510 data = DataFrame(None)

/Users/ab763/Programs/Git/pysat/pysat/instruments/omni_hro.py in load(fnames, tag, sat_id)
120 fname = fnames[0][0:-11]
121 date = pysat.datetime.strptime(fnames[0][-10:], '%Y-%m-%d')
--> 122 with pysatCDF.CDF(fname) as cdf:
123 data, meta = cdf.to_pysat()
124 # pick out data for date

AttributeError: exit

And this went away when I removed the "with" statement.

**Comment by aburrell** [comment]
Yes, I hadn't encountered it before so I read up on it.  Since I'm not well versed with the "with" statements I'm not sure why pyCDF would fail under these conditions.

**Comment by rstoneback** [comment]
I’m not sure either. The error raised looks like the Omni file is missing an attribute pysatCdF is trying to grab. That should fail all the time though. If the attribute isn’t there why is pysatCDF trying to read it?

I’m hoping to try a few direct loads during office hours. Is there a specific day or do you get the error for all days?

On Mar 27, 2018, at 9:47 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I hadn't encountered it before so I read up on it. Since I'm not well versed with the "with" statements I'm not sure why pyCDF would fail under these conditions.

**Comment by aburrell** [comment]
There was a problem with missing attributes, but I fixed it when I added the additional custom routines.  The problem with that was that the files you had downloaded used all caps, while the files it downloaded for me had the attributes all in lower case.  However, the reading still failed with the "with" statement after that was fixed.  I'll take a peak at the code real quick and see if my attribute error fix got removed in the recent upgrades.

**Comment by aburrell** [comment]
Oh, and there's no specific day.  I get this no matter what day I try.

**Comment by aburrell** [comment]
Honestly, I don't know what to tell you about this.  If I run this using "with" it fails.  If I run it without "with" it succeeds.

**Comment by aburrell** [comment]
Oh, I have an idea.  Wait a sec.

**Comment by aburrell** [comment]
Ok, I found out what it was!  The problem was that I had an old version of pysatCDF installed.  I downloaded the latest version from pip and now it works on python 2.7 and 3.5 (so I'm going to assume it works everywhere now).

I wonder if there's a clever way to test for versions of dependencies so something like this doesn't pop up again?

**Comment by rstoneback** [comment]
Good question.

We could list pysatCDF as a required library in pysat and put a version requirement in there. Downside, windows users wouldn’t be able to use pysat because pysatCDF doesn’t compile on windows.

There is apparently support for “extras" (http://peak.telecommunity.com/DevCenter/setuptools#declaring-dependencies) though I don’t think it is exactly what I’m looking for.


On Mar 27, 2018, at 11:04 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, I found out what it was! The problem was that I had an old version of pysatCDF installed. I downloaded the latest version from pip and now it works on python 2.7 and 3.5 (so I'm going to assume it works everywhere now).

I wonder if there's a clever way to test for versions of dependencies so something like this doesn't pop up again?

**Comment by aburrell** [comment]
So much of pysat uses pysatCDF, I think it would be worth doing.  Is there some way to work out the windows kinks?  Or is the problem with some code outside of your control?

**Comment by rstoneback** [comment]
I’m with ya.

The root problem is getting NASA’s CDF library to compile at all on windows. I’ve sent an email to Matthew asking for some help.


On Mar 27, 2018, at 1:38 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:

So much of pysat uses pysatCDF, I think it would be worth doing. Is there some way to work out the windows kinks? Or is the problem with some code outside of your control?
