### ISSUE TITLE
COSMIC GPS instrument consolidation

### ISSUE THREAD

**Issue by jklenzing** [rstoneback/pysat#224]
Currently, the 2013 reprocessed data from COSMIC exists as a separate instrument file.  There is significant overlap between the `cosmic_gps.py` and `cosmic2013_gps.py` files, none of which can be tested on Travis due to access issues.

The code could potentially be compacted by combining these into a single cosmic_gps instrument, with two sat_ids.  This would add to the usability of the interface for new users, as well as reduce the number of untested lines by about 120 (~0.9%).

Reading over the documentation at https://cdaac-www.cosmic.ucar.edu/cdaac/products.html, I propose using tags of "2013" and "post" for the 2013 re-processed data and the post-processed data respectively.  "2013" would be the default sat_id.

Additionally, this puts the infrastructure in place for adding the real time cosmic data in the future.

**Comment by rstoneback** [comment]
I like the combination of files but I don’t like ‘2013’ vs ‘post’. Unclear which is newer. The same could be said of my current naming scheme as well. It could be handled in the docstrings though. I do like ‘2013’ as the default.

On May 28, 2019, at 1:50 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently, the 2013 reprocessed data from COSMIC exists as a separate instrument file. There is significant overlap between the cosmic_gps.py and cosmic2013_gps.py files, none of which can be tested on Travis due to access issues.

The code could potentially be compacted by combining these into a single cosmic_gps instrument, with two sat_ids. This would add to the usability of the interface for new users, as well as reduce the number of untested lines by about 120 (~0.9%).

Reading over the documentation at https://cdaac-www.cosmic.ucar.edu/cdaac/products.html, I propose using tags of "2013" and "post" for the 2013 re-processed data and the post-processed data respectively. "2013" would be the default sat_id.

Additionally, this puts the infrastructure in place for adding the real time cosmic data in the future.

**Comment by jklenzing** [comment]
Possibilities: 
- 'reprocess' vs 'postprocess'
- '2013' vs 'pre-2013'
- 'batman' vs 'everyone'

The re-process vs post-process notation is not intuitive, but it matches what's on the server, which includes preference recommendations.

**Comment by rstoneback** [comment]
Batman v everyone is my favorite but 2013 and pre-2013 are the most clear.

On May 28, 2019, at 9:16 AM, Jeff Klenzing <notifications@github.com<mailto:notifications@github.com>> wrote:


Possibilities:

  *   'reprocess' vs 'postprocess'
  *   '2013' vs 'pre-2013'
  *   'batman' vs 'everyone'

The re-process vs post-process notation is not intuitive, but it matches what's on the server, which includes preference recommendations.

**Comment by jklenzing** [comment]
According to CDAAC, the data availability for '2013' is 2006.112 - 2014.120, while for 'pre-2013' it is 2014.121 - 2019.058.  Which is not fully clear to me.

What about re-processed vs processed?  Dropping the post might be a little better as to which one is a higher-level data product.

**Comment by jklenzing** [comment]
So it seems that if post-processed data is available, then the re-processed is not and vice versa.  We could consider dropping sat_id tags and just point by date or availability?

**Comment by jklenzing** [comment]
The break between data availability for the re-processed and post-processed matches the documentation at https://cdaac-www.cosmic.ucar.edu/cdaac/products.html

Moving forward with plan to try downloading re-processed data, then trying post-processed if HTTP error occurs.

**Comment by jklenzing** [comment]
Other issues with COSMIC (not caught before since this is untested):
- `shutil.move` will create a nested directory for new data if day has been previously downloaded
- tar files not deleted afterward -> takes up more disk space
- `load` routines in cosmic and cosmic2013 use different packages (netCDF4, scipy).  

@JonathonMSmith, have I missed any?

**Comment by jklenzing** [comment]
Closed with merge of #234.
