### ISSUE TITLE
Test Occurrence Probability Routines

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#51]
Need to add 'random' variables to pysat testing, with known properties, so that the seasonal occurrence probability routines can be tested.

Plan:
 - Add a signal to pysat_testing and pysat_testing2D that goes above a gate value some known percentage of the time. The percentage of times above the gate needs to vary spatially over longitude and latitude 
 - Another signal that varies over 3D bins
 - Create tests that verifies the operation of the test signal as well as the seasonal occurrence routines.

**Comment by aburrell** [comment]
This should be done before the next major release (2.0), since it will greatly improve the testing coverage.

**Comment by jklenzing** [comment]
This is easier to test without 'random' variables.  A sample is uploaded for the 2D occur_prob routines at https://github.com/rstoneback/pysat/blob/test_occur_prob/pysat/tests/test_ssnl_occur_prob.py

In both cases, I am looking at longitude and latitude as my x and y bins, and my gate selection is slt greater than 12.  As long as sufficient data is loaded (about a year in the code above), the by_orbit routine should return 0.5 within some tolerance for all bins (since over many precession cycles, all local times will be sampled equally), and the daily routine should return 1.0 (since at some point in a given day, it is afternoon somewhere).

Open issues for discussion:
- The number of bins and amount of data will affect the tolerance.  In this case, a 3x3 grid and a year of testing data produce 0.5 \pm 0.01 in all bins.  Run time is about 1 min.  We can use more bins, but the tolerance increases as there are less points in each bin.
- This can be generalized to the 3d case, but in a roundabout way.  Use slt as the third dimension and as the gate parameter.  In the simplest case, use two bins for slt, and 12 for the gate.  Barring some edge effects, the low bins should all be 0, and the high bins should all be 1.
- Potentially, this could be adapted for the 2d bins as well, and look at latitude vs slt rather than longitude.

Thoughts?

**Comment by jklenzing** [comment]
Closed with merge of #188.
