### ISSUE TITLE
Set Data Bug

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#63]
The command
   sat[idx, :] = later_fit.data

where later_fit and sat are both Instrument objects. idx is a numpy array for indexing.

Produces the following error:

envs/Python_2/lib/python2.7/site-packages/pysat/_meta.pyc in __setitem__(self, names, input_data)
    421             # convert given names into ones Meta has already seen
    422             # if new, then input names become the standard
--> 423             names = [self.var_case_name(name) for name in names]

TypeError: 'slice' object is not iterable 

Things don't work with
   sat[idx] = later_fit.data
either.

**Comment by jklenzing** [comment]
Since I'm modifying the setitem structure as part of #125, I'll look into this.

**Comment by jklenzing** [comment]
The issue comes from ':' being passed through as an empty slice.  I've added a check in _meta.py after the "if isinstance(names, basestring):" line to look for an empty slice and import a list of all keys

Lines 419-421 in :

elif isinstance(names, slice) and (names.start == None):
   # Check for ':' passed through as empty slice
   names = list(self.data.keys())
            
It's a little brute force, but it works in my test script based on the problem outlined above.  We should probably work out some unit tests that try to break this.

Not sure about the second problem though.

**Comment by jklenzing** [comment]
I've added this to the latest push for #125.

**Comment by jklenzing** [comment]
"sat[idx, :] = later_fit.data" and "sat[idx] = later_fit.data" now work for pandas formats, and "sat[idx] = later_fit.data" will work for xarray formats as part of the latest push to #125.  I've added a unit test to test_instrument.py to check for this in the future.  

We can close this once reviewed and merged.

**Comment by jklenzing** [comment]
For future ref:

pandas[idx] passes key[1] as slice(int, int, none)
pandas[idx,:] passes key[1] as slice(none, none, none)
xarray[idx] passes key[1] as slice(int, int, none)
xarray[idx,:] passes key[1] as a 0d array (in testing_xarray)

using isinstance(key[1].step, none) to detect.

**Comment by jklenzing** [comment]
Closing with merge of #125.
