### ISSUE TITLE
remote instrument date range

### ISSUE THREAD

**Issue by aburrell** [rstoneback/pysat#70]
It would be very useful to be able to retrieve a range of dates for data that can be remotely accessed.

**Comment by rstoneback** [comment]
Agreed. This feature would be part of an enhancement I submitted an issue on. Don’t have the number since I’m on the phone. Not a major deal but some work needs to be done on the Files class to make this happen.

On Sep 13, 2018, at 4:53 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be very useful to be able to retrieve a range of dates for data that can be remotely accessed.

**Comment by aburrell** [comment]
I could really use this as part of the model validation project.  Also, I think it would be useful to add that as a project on the github page.  I'll try to do that next week.

**Comment by rstoneback** [comment]
Thanks for the heads up. I agree with the project listing. As you can see I haven’t quite made it there. :)

We should also talk about the ccmc meeting I had today. Nominal plan to start working with them on an ionosphere model. Perhaps tie-gcm since they have some work in that area. A guy from Michigan mentioned some GITM code you’ve written. And of course sami3 since you are currently in that area.

Too much to do.

On Sep 13, 2018, at 5:01 PM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:

I could really use this as part of the model validation project. Also, I think it would be useful to add that as a project on the github page. I'll try to do that next week.

**Comment by aburrell** [comment]
Yes, I started the python analysis code for GITM.  So I'll be able to help with GITM and SAMI3.  But I support starting with TIE-GCM since that means someone else will need to do the heavy lifting :-D

**Comment by rstoneback** [comment]
Closed per #128

**Comment by aburrell** [comment]
@rstoneback , could you put a little example here, so we know how to do this?  I'm assuming the docs haven't been updated with an example of how to use this yet.

**Comment by aburrell** [comment]
So the user will need to extract the date range from the files.  Does pysat have the file format at this point?  If so, it would be more in the spirit of this issue to provide a routine that backs out the dates from the file names, and another that then gets the first and last datetime available.

**Comment by rstoneback** [comment]
No, the dates have already been extracted into date times. If you want the first and last date just grab the first and last index of the series that is returned.

On Jan 4, 2019, at 6:07 AM, Angeline Burrell <notifications@github.com<mailto:notifications@github.com>> wrote:


So the user will need to extract the date range from the files. Does pysat have the file format at this point? If so, it would be more in the spirit of this issue to provide a routine that backs out the dates from the file names, and another that then gets the first and last datetime available.
